FROM apache/airflow:2.8.0-python3.11

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    "sqlalchemy>=1.4.0,<2.0.0" \
    pandas==2.2.0 \
    numpy==1.26.4 \
    scikit-learn==1.4.0 \
    scipy==1.12.0 \
    psycopg2-binary==2.9.9 \
    minio==7.2.4 \
    kafka-python==2.0.2 \
    python-dotenv==1.0.0 \
    pyarrow==15.0.0