apiVersion: 1

datasources:
  - name: SentinelFlow-PostgreSQL
    type: postgres
    url: postgres:5432
    database: sentinelflow
    user: sentinelflow_user
    secureJsonData:
      password: sentinelflow123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true